#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/alvNa/spring-cloud-demo/tree/main/configurations-data
#          skipSslValidation: true

spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alvNa/spring-cloud-demo.git
          searchPaths: configurations-data
          skipSslValidation: true
          default-label: main

#  application:
#    name: config-server
#  profiles:
#    active: git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/refactorizando-web/spring-cloud-config-server-git